import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Footer } from "@/components/Footer";



const barlow = Barlow_Condensed({
  weight: '400',
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Azeez Abass | Full-stack Developer & Engineer",
  description: "Generated by create next app",
   keywords: ['Software Engineer', 'Web Development', 'App Development', 'Front End Developer', 'Software Architecture', 'Game Development', 'Full Stack Developer', 'Azeez Abass'],
  authors: [{ name: 'Azeez Abass' }],
  creator: 'Azeez Abass',
  publisher: 'Azeez Abass',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
    icons: {
    icon: '/abass-pic.png',
    shortcut: '/abass-pic.png',
    apple: '/abass-pic.png',
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://azeezabass.vercel.app/',
    siteName: 'Azeez Abass Portfolio',
    title: 'Azeez Abass | Creative Software Engineer',
    description:'Creative Software Engineer with 3+ years of experience helping startups and growing businesses solve real-world problems through technology. I design and build digital products that improve customer experience, automate operations, and drive business growth. My focus is on creating scalable solutions that help brands launch faster, manage their processes more efficiently, and deliver value to their users. I’m passionate about turning ideas into functional, user-centered applications that solve everyday challenges for businesses and their customers.',
    images: [
      {
        url: '/myimage.png',
        width: 1200,
        height: 630,
        alt: 'Azeez Abass - Creative Software Engineer',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Azeez Abass | Creative Software Engineer',
    description: 'Creative Software Engineer building scalable products with great user experiences. I help startups and businesses turn ideas into powerful digital solutions that simplify processes, enhance productivity, and drive growth.',
    creator: '@Kolawolegold10',
    images: ['/myimage.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'your-google-verification-code',
  },
  themeColor: '#0a0a0a',
  manifest: '/manifest.json',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'Azeez Abass Kolawole',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={` ${barlow.className}`}
    >
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
